{% set name = "latex2mathml" %}
{% set version = "3.79.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/latex2mathml-{{ version }}.tar.gz
  sha256: 11bde318c2d2d6fcdd105a07509d867cee2208f653278eb80243dec7ea77a0ce

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - latex2mathml = latex2mathml.converter:main
    - l2m = latex2mathml.converter:main

requirements:
  host:
    - python >=3.8,<4.0
    - poetry-core
    - pip
  run:
    - python >=3.8,<4.0

test:
  imports:
    - latex2mathml
  commands:
    - pip check
    - latex2mathml -V
    - l2m -V
  requires:
    - pip

about:
  home: https://github.com/roniemartinez/latex2mathml
  summary: Pure Python library for LaTeX to MathML conversion
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - '0xbe7a'
